### ISSUE TITLE
Scroll seems to be less responsive when you have the frozen column

### ISSUE THREAD

**Issue by Luka-M** [farseerdev/sheet-happens#19]
https://github.com/farseerdev/sheet-happens/assets/1553390/bdf36745-72a3-48eb-b9db-b119821a6e34

It should start scrolling immediately

**Comment by unconed** [comment]
I don't think this is related to the frozen column, but just that the scrolling is now based on X/Y position rather than cell #. So wider cells take longer to scroll past than narrow cells. But the average velocity should still be constant.

In the old layout model, the mapping between scroll position and cell was somewhat underdefined. Narrow columns would take longer to scroll past than wider ones, and the logic for scrolling to off-screen cells was very odd.

We could move closer the older model, or make it a flag. It means calculating scroll position and range in cells instead of pixels.
